name: ifcfg
method: http://packages.osrfoundation.org/gazebo/ubuntu-stable
suites: [bionic, stretch, buster]
component: main
architectures: [amd64, arm64, source]
filter_formula: Package (% python3-ifcfg* )
# needed unless we incorporate the right gpg key
verify_release: blindtrust
